
IF(_WIN_)
	FIND_PATH(OpenCV_INCLUDE_DIR NAMES opencv2 HINTS ${CMAKE_SOURCE_DIR}/../../SDK/opencv/include)
	FIND_FILE(OpenCV_DEBUG_LIB opencv_world346d.lib)
	FIND_FILE(OpenCV_RELEASE_LIB opencv_world346.lib)
ELSEIF(_OSX_)
	FIND_PATH(OpenCV_INCLUDE_DIR NAMES opencv2 HINTS "/usr/local/Cellar/opencv@3/3.4.20/include")
	FIND_PATH(OpenCV_LIB_DIR NAMES libopencv_calib3d.3.4.20.dylib HINTS "/usr/local/Cellar/opencv@3/3.4.20/lib")

	SET(OpenCV_CORE_LIB ${OpenCV_LIB_DIR}/libopencv_core.dylib)
	SET(OpenCV_HIGHGUI_LIB ${OpenCV_LIB_DIR}/libopencv_highgui.dylib)
	SET(OpenCV_IMGPROC_LIB ${OpenCV_LIB_DIR}/libopencv_imgproc.dylib)
	SET(OpenCV_IMGCODECS_LIB ${OpenCV_LIB_DIR}/libopencv_imgcodecs.dylib)

	ADD_LIBRARY(_highgui STATIC IMPORTED)
	SET_TARGET_PROPERTIES(_highgui PROPERTIES IMPORTED_LOCATION "${OpenCV_HIGHGUI_LIB}")

	ADD_LIBRARY(_imgproc STATIC IMPORTED)
	SET_TARGET_PROPERTIES(_imgproc PROPERTIES IMPORTED_LOCATION "${OpenCV_IMGPROC_LIB}")

	ADD_LIBRARY(_imgcodecs STATIC IMPORTED)
	SET_TARGET_PROPERTIES(_imgcodecs PROPERTIES IMPORTED_LOCATION "${OpenCV_IMGCODECS_LIB}")
ENDIF()

IF(_WIN_)
	ADD_LIBRARY(OpenCV STATIC IMPORTED)
	SET_TARGET_PROPERTIES(OpenCV PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
			INTERFACE_INCLUDE_DIRECTORIES "${OpenCV_INCLUDE_DIR};"
			IMPORTED_LOCATION_RELEASE "${OpenCV_RELEASE_LIB}"
			IMPORTED_LOCATION_DEBUG "${OpenCV_DEBUG_LIB}"
	)
ELSEIF(_OSX_)
	ADD_LIBRARY(OpenCV STATIC IMPORTED)
	SET_TARGET_PROPERTIES(OpenCV PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
			INTERFACE_INCLUDE_DIRECTORIES "${OpenCV_INCLUDE_DIR};"
			IMPORTED_LINK_INTERFACE_LIBRARIES "_highgui;_imgproc;_imgcodecs"
			IMPORTED_LOCATION "${OpenCV_CORE_LIB}"
	)
ENDIF()