
IF(_WIN_)
	FIND_PATH(JSON_INCLUDE_DIR NAMES json HINTS ../jsoncpp/include)
	FIND_FILE(JSON_RELEASE_LIB json_vc141_libmt.lib HINTS ../jsoncpp/lib)
	FIND_FILE(JSON_DEBUG_LIB json_vc141_libmtd.lib HINTS ../jsoncpp/lib)
ELSEIF(_OSX_)
	FIND_PATH(JSON_INCLUDE_DIR NAMES json HINTS ../jsoncpp/include)
	FIND_FILE(JSON_LIB libjsoncpp.dylib HINTS ../jsoncpp/lib)
ENDIF()


IF(_WIN_)
	ADD_LIBRARY(Json STATIC IMPORTED)
	SET_TARGET_PROPERTIES(Json PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
			INTERFACE_INCLUDE_DIRECTORIES "${JSON_INCLUDE_DIR}"
			IMPORTED_LOCATION_RELEASE "${JSON_RELEASE_LIB}"
			IMPORTED_LOCATION_DEBUG "${JSON_DEBUG_LIB}"
	)
ELSEIF(_OSX_)
	ADD_LIBRARY(Json STATIC IMPORTED)
	SET_TARGET_PROPERTIES(Json PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
			INTERFACE_INCLUDE_DIRECTORIES "${JSON_INCLUDE_DIR}"
			IMPORTED_LOCATION "${JSON_LIB}"
	)
ENDIF()