
IF(_WIN_)
	FIND_PATH(LIBZIP_INCLUDE_DIRS NAMES zip.h HINTS ${CMAKE_SOURCE_DIR}/../../SDK/libzip/include)
	FIND_PATH(LIBZIP_LIB_DIR NAMES zip.lib HINTS ${CMAKE_SOURCE_DIR}/../../SDK/libzip/lib)
	SET(LIBZIP_LIBRARY ${LIBZIP_LIB_DIR}/zip.lib)
ELSEIF(_OSX_)
	FIND_PATH(LIBZIP_INCLUDE_DIRS NAMES zip.h HINTS "/usr/local/Cellar/libzip/1.10.1/include")
	FIND_PATH(LIBZIP_LIB_DIR NAMES libzip.dylib HINTS "/usr/local/Cellar/libzip/1.10.1/lib")
	SET(LIBZIP_LIBRARY ${LIBZIP_LIB_DIR}/libzip.dylib)
ENDIF()

ADD_LIBRARY(LibZip STATIC IMPORTED)
SET_TARGET_PROPERTIES(LibZip PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${LIBZIP_INCLUDE_DIRS}"
	IMPORTED_LOCATION "${LIBZIP_LIBRARY}"
)
