
IF(_WIN_)
	FIND_PATH(SuiteSparse_INCLUDE_DIR NAMES suitesparse HINTS ${CMAKE_SOURCE_DIR}/../../SDK/suitesparse/include)
	FIND_PATH(SuiteSparse_LIB_DIR NAMES libamd.lib HINTS ${CMAKE_SOURCE_DIR}/../../SDK/suitesparse/lib)
ELSEIF(_OSX_)
	FIND_PATH(SuiteSparse_INCLUDE_DIR NAMES SuiteSparse_config.h HINTS "/usr/local/Cellar/suite-sparse/7.1.0/include")
	FIND_PATH(SuiteSparse_LIB_DIR NAMES libamd.dylib HINTS "/usr/local/Cellar/suite-sparse/7.1.0/lib")
ENDIF()

IF(_WIN_)
	SET(CSPARSE_RELEASE_LIB ${SuiteSparse_LIB_DIR}/libcxsparse.lib)
	SET(CSPARSE_DEBUG_LIB ${SuiteSparse_LIB_DIR}/libcxsparsed.lib)
ELSEIF(_OSX_)
	SET(CSPARSE_LIB ${SuiteSparse_LIB_DIR}/libcxsparse.dylib)
ENDIF()

IF(_WIN_)
	ADD_LIBRARY(SuiteSparse STATIC IMPORTED)
	SET_TARGET_PROPERTIES(SuiteSparse PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
			INTERFACE_INCLUDE_DIRECTORIES "${SuiteSparse_INCLUDE_DIR}"
			IMPORTED_LOCATION_RELEASE "${CSPARSE_RELEASE_LIB}"
			IMPORTED_LOCATION_DEBUG "${CSPARSE_DEBUG_LIB}"
	)
ELSEIF(_OSX_)
	ADD_LIBRARY(SuiteSparse STATIC IMPORTED)
	SET_TARGET_PROPERTIES(SuiteSparse PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
			INTERFACE_INCLUDE_DIRECTORIES "${SuiteSparse_INCLUDE_DIR}"
			IMPORTED_LOCATION "${CSPARSE_LIB}"
	)
ENDIF()


